### ISSUE TITLE
Read config file and store jobs in internal structure

### ISSUE THREAD

**Issue by neckhair** [neckhair/gcron#1]
The config file should be read (by using [viper](https://github.com/spf13/viper)) and stored in an internal structure.

Draft of a config file:
```yml
logfile: /dev/stdout
command: echo "Hello World"
pattern: '* * * * * *'
```
