### ISSUE TITLE
Create built-in cURL-like command

### ISSUE THREAD

**Issue by neckhair** [neckhair/gcron#13]
GCron is currently made to run shell commands like the original cron does. But this often requires a Docker image to have more dependencies installed. For example when you want to fetch a URL on a regular basis (Drupal Cronjobs for example) you'll need to have `curl` installed in the container.

The idea of this feature is to have a built in task which can call URLs.

Example config:

```yml
tasks:
- type: GetUrl
  schedule: @every 10m
  get_url:
    url: http://mydrupalsite.com/cron/_abcd
    method: GET
```

This feature builds the foundation for more such tasks.
